# Generated by Django 4.2.17 on 2026-07-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_luggagebooking_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_number', models.CharField(max_length=10)),
                ('coach_type', models.CharField(choices=[('GEN', 'General / Unreserved'), ('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC First Class'), ('CC', 'Chair Car'), ('EC', 'Executive Chair Car')], max_length=5)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('is_bookable', models.BooleanField(default=True)),
                ('has_seat_layout', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('LOWER', 'Lower Berth'), ('MIDDLE', 'Middle Berth'), ('UPPER', 'Upper Berth'), ('SIDE_LOWER', 'Side Lower Berth'), ('SIDE_UPPER', 'Side Upper Berth'), ('WINDOW', 'Window Seat'), ('MIDDLE_SEAT', 'Middle Seat'), ('AISLE', 'Aisle Seat')], max_length=20)),
                ('row_number', models.PositiveIntegerField(default=1)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='ticket_booking.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_to', to='home.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_from', to='home.station')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bookings', to='home.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bookings', to='ticket_booking.seat')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bookings', to='ticket_booking.train')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='ticket_booking.train'),
        ),
    ]
