# Generated by Django 4.2.17 on 2026-07-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0002_ticketbooking_fare_alter_ticketbooking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='ticket_booking.train')),
            ],
        ),
    ]
