# Generated by Django 4.2.17 on 2026-07-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_luggagebooking_rejection_reason'),
        ('ticket_booking', '0004_fix_trainstop_and_add_is_reserved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainstop',
            options={'ordering': ['stop_order']},
        ),
        migrations.AlterUniqueTogether(
            name='trainstop',
            unique_together={('train', 'station')},
        ),
        migrations.CreateModel(
            name='TrainStopDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_destinations', to='home.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_sources', to='home.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_distances', to='ticket_booking.train')),
            ],
            options={
                'ordering': ['train', 'source_station', 'destination_station'],
                'unique_together': {('train', 'source_station', 'destination_station')},
            },
        ),
    ]
