# Generated by Django 4.2.17 on 2026-08-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0006_bookingpassenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='seat',
        ),
    ]
