# Generated by Django 4.2.17 on 2026-08-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_luggagebooking_rejection_reason'),
        ('ticket_booking', '0007_remove_ticketbooking_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('status', models.CharField(choices=[('LOCKED', 'Temporarily Locked'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='LOCKED', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_reservations', to='ticket_booking.ticketbooking')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservation_destinations', to='home.station')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ticket_booking.seat')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservation_sources', to='home.station')),
            ],
        ),
    ]
