# Generated by Django 4.2.17 on 2026-08-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0008_seatreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAllocationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.PositiveIntegerField(blank=True, null=True)),
                ('passenger_gender', models.CharField(blank=True, max_length=10)),
                ('preferred_coach_type', models.CharField(blank=True, max_length=20)),
                ('preferred_berth_type', models.CharField(blank=True, max_length=30)),
                ('is_senior', models.BooleanField(default=False)),
                ('is_lactating_mother', models.BooleanField(default=False)),
                ('allocated_seat_number', models.PositiveIntegerField(blank=True, null=True)),
                ('allocated_seat_type', models.CharField(blank=True, max_length=30)),
                ('allocated_coach_number', models.CharField(blank=True, max_length=10)),
                ('allocated_coach_type', models.CharField(blank=True, max_length=20)),
                ('algorithm_score', models.IntegerField(default=0)),
                ('coach_preference_satisfied', models.BooleanField(default=False)),
                ('berth_preference_satisfied', models.BooleanField(default=False)),
                ('comfort_requirement_satisfied', models.BooleanField(default=False)),
                ('family_proximity_satisfied', models.BooleanField(default=False)),
                ('preference_satisfaction_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_evaluations', to='ticket_booking.seat')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_evaluations', to='ticket_booking.train')),
            ],
        ),
    ]
