# Generated by Django 4.2.17 on 2026-09-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_medicalassistancerequest_passenger_and_more'),
        ('ticket_booking', '0009_seatallocationevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDelayUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('STOPPED', 'Stopped'), ('RESUMED', 'Resumed')], default='DELAYED', max_length=20)),
                ('reason', models.CharField(choices=[('SIGNAL_ISSUE', 'Signal Issue'), ('PLATFORM_UNAVAILABLE', 'Platform Unavailable'), ('TRACK_ISSUE', 'Track Issue'), ('TECHNICAL_PROBLEM', 'Technical Problem'), ('OPERATIONAL_DELAY', 'Operational Delay'), ('WEATHER', 'Weather Condition'), ('TRAFFIC_CONGESTION', 'Rail Traffic Congestion'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('expected_departure', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_delay_updates', to='home.officer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_delay_updates', to='home.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_updates', to='ticket_booking.train')),
            ],
        ),
    ]
