# Generated by Django 4.2.17 on 2026-09-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_medicalassistancerequest_passenger_and_more'),
        ('ticket_booking', '0010_traindelayupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindelayupdate',
            old_name='expected_departure',
            new_name='expected_time',
        ),
        migrations.RemoveField(
            model_name='traindelayupdate',
            name='description',
        ),
        migrations.AddField(
            model_name='traindelayupdate',
            name='distance_from_station',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='traindelayupdate',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_updates', to='home.officer'),
        ),
        migrations.AlterField(
            model_name='traindelayupdate',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traindelayupdate',
            name='status',
            field=models.CharField(choices=[('AT_STATION', 'At Station'), ('BEFORE_STATION', 'Stopped Before Station'), ('BETWEEN_STATIONS', 'Stopped Between Stations'), ('MOVING_SLOWLY', 'Moving Slowly')], max_length=30),
        ),
        migrations.AlterField(
            model_name='traindelayupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
