# Generated by Django 4.2.17 on 2026-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='verification_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='luggagebooking',
            table='home_luggagebooking',
        ),
        migrations.AlterModelTable(
            name='station',
            table='home_station',
        ),
    ]
