# Generated by Django 4.2.17 on 2026-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
