# Generated by Django 4.2.17 on 2026-08-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_luggagebooking_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=4)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='home.station')),
            ],
        ),
    ]
