# Generated by Django 4.2.17 on 2026-08-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0009_seatallocationevaluation'),
        ('home', '0005_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='ticket_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luggage_bookings', to='ticket_booking.ticketbooking'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='transfer_type',
            field=models.CharField(choices=[('WITH_TICKET', 'Passenger Luggage - With Ticket'), ('WITHOUT_TICKET', 'Parcel / Unaccompanied Transfer - Without Passenger Ticket')], default='WITH_TICKET', max_length=20),
        ),
    ]
