# Generated by Django 4.2.17 on 2026-08-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_luggagebooking_ticket_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField()),
                ('luggage_type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.luggagebooking')),
            ],
        ),
    ]
