# Generated by Django 4.2.17 on 2026-08-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_luggageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggageitem',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luggageitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='luggage_items/'),
        ),
    ]
