# Generated by Django 4.2.17 on 2026-08-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_luggageitem_item_description_luggageitem_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('WAITING_ROOM', 'Waiting Room'), ('TICKET_COUNTER', 'Ticket Counter'), ('WASHROOM', 'Washroom'), ('FOOD_STALL', 'Food Stall'), ('LIFT', 'Lift'), ('ESCALATOR', 'Escalator'), ('FOOT_OVER_BRIDGE', 'Foot Over Bridge'), ('CLOAK_ROOM', 'Cloak Room'), ('DRINKING_WATER', 'Drinking Water'), ('PARKING', 'Parking'), ('OTHER', 'Other')], max_length=50)),
                ('direction', models.CharField(blank=True, max_length=50)),
                ('platform_number', models.CharField(blank=True, max_length=50)),
                ('location_description', models.TextField()),
                ('nearby_landmark', models.CharField(blank=True, max_length=200)),
                ('additional_information', models.TextField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='home.station')),
            ],
        ),
    ]
