# Generated by Django 4.2.17 on 2026-09-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stationfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=20)),
                ('coach_number', models.CharField(max_length=20)),
                ('emergency_type', models.CharField(choices=[('MEDICAL_EMERGENCY', 'Medical Emergency'), ('INJURY', 'Injury'), ('BREATHING_DIFFICULTY', 'Breathing Difficulty'), ('CHEST_PAIN', 'Chest Pain'), ('UNCONSCIOUS', 'Unconscious Passenger'), ('FALL_ACCIDENT', 'Fall / Accident'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDING', 'Officer Responding'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_requests', to='home.station')),
            ],
        ),
    ]
