# Generated by Django 4.2.17 on 2026-09-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_medicalassistancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_head', to='home.station')),
            ],
        ),
    ]
