# Generated by Django 4.2.17 on 2026-09-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_medicalhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalassistancerequest',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_requests', to='home.passenger'),
        ),
        migrations.AlterField(
            model_name='medicalassistancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDING', 'Medical Team Responding'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
