# Generated by Django 4.2.17 on 2026-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_medicalassistancerequest_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggageitem',
            name='rc_book',
            field=models.FileField(blank=True, null=True, upload_to='rc_books/'),
        ),
    ]
